package com.global.project.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@AllArgsConstructor
@NoArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "UNCATEGORIZED ERROR"),
    INVALID_KEY(1001, "INVALID MESSAGE KEY"),

    USER_USERNAME_EXISTED(2002, "USER USERNAME ALREADY EXISTS"),
    USER_NOT_FOUND(2003, "USER NOT FOUND"),
    USER_CANT_CREATE_USER(2004, "USER CANT CREATE USER"),

    ACCOUNT_EMAIL_EXISTED(2003, "ACCOUNT EMAIL EXISTS"),
    ACCOUNT_NOT_FOUND(2004, "ACCOUNT NOT FOUND"),


            INVALID_MISSING_TOKEN(2001,"Invalid or missing Authorization token"),
    TOKEN_RESET_PASSWORD_INVALID(2005, "TOKEN RESET PASSWORD INVALID"),
    TOKEN_RESET_PASSWORD_EXPIRED(2006, "TOKEN RESET PASSWORD EXPIRED"),
    TOKEN_RESET_NOT_MATH(2007, "TOKEN RESET PASSWORD NOT MATCH"),

    INVALID_CREDENTIAL(1002, "INVALID CREDENTIAL"),
    TOKEN_EXPIRED(1003, "TOKEN EXPIRED"),
    ACCOUNT_INVALID(1004, "ACCOUNT INVALID"),
    LOGIN_FAILED(1005, "LOGIN FAILED"),

    REFRESH_TOKEN_NOT_FOUND(1006,"REFRESH TOKEN NOT FOUND"),
    LOGOUT_FAILED(1007,"LOGOUT FAILED"),
    ERROR_(1009,"An error occurred while retrieving account details");



    HASTAG_CREATE_LIST_FAILED(2000, "ERROR WHEN INSERT LIST HASTAG TO DB"),
    TWEET_NOT_FOUND(2001, "TWEET NOT FOUND");



    private int code;
    private String message;
}
