spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cy_twitter?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #  thymeleaf:
  #    cache: false
  #    prefix: classpath:/templates/
  #    check-template-location: true
  #    check-template: true
  #    suffix: .html
  #    encoding: UTF-8
  #    content-type: text/html
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  main:
    allow-bean-definition-overriding: true # Allow override for i18n
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #Send mail
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    # Other smtp properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          # TLS port 587
          starttls:
            enable: true
server:
  port: 8085
#For https
#  ssl:
#    key-store: keystore.p12
#    key-store-password: 147258159asdasd
#    key-store-type: pkcs12
#    key-alias: backend

#Secret Key HS512
jwt:
  SECRET_ACCESS_TOKEN_KEY: askhdqiwu48123y123cxv2134123/123u1t238gqhjwdnjaqwhuie412/312i3o1y28712iekjasbdiuqw9e812739jasldk/zxkcbaskanskdlasda/scaksjcoiasjdoi12312o123/qwkjehqwuiehjiqwueiqwuejkqwndoqwd/129831yu293h12ui3qhwiuehqwuieiwheiqwe
  JWT_EXPIRATION_ACCESS_TOKEN: 28800000
config:
  path: C:\\Users\\PCM\\Desktop\\

